language: cpp
compiler:
    - gcc
before_install:
  - sudo apt-get install libboost-all-dev
before_script:
  - mkdir build_travis
  - cd build_travis
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  
script: make -j 8 VERBOSE=1
branches:
  only:
    - master

notifications:
  receipients:
    - isulsz1@gmail.com
  email:
    on_failure: always


