language: cpp
compiler:
    - gcc
before_install:
  - sudo apt-get install libboost-all-dev
before_script:
    - ./configure-travis.sh
    - pwd
script: make -j 8
branches:
  only:
    - master

notifications:
  receipients:
    - isulsz1@gmail.com
  email:
    on_failure: always


